package com.onboard.plugin.git.mapper;

import com.onboard.domain.mapper.common.BaseCriteria;
import com.onboard.domain.mapper.common.BaseExample;
import java.util.ArrayList;
import java.util.List;

public class PullRequestReviewerExample implements BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    protected int start = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public PullRequestReviewerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public List<BaseCriteria> getOredBaseCriteria() {
        List<com.onboard.domain.mapper.common.BaseCriteria> list = new ArrayList<com.onboard.domain.mapper.common.BaseCriteria>();
        list.addAll(oredCriteria);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setLimit(int start, int limit) {
        this.start = start;
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public PullRequestReviewerExample(PullRequestReviewerObject sample) {
        oredCriteria = new ArrayList<Criteria>();
        Criteria criteria = this.or();
        if (sample.getPullRequestId() != null) {
            criteria.andPullRequestIdEqualTo(sample.getPullRequestId());
        }
        if (sample.getReviewerId() != null) {
            criteria.andReviewerIdEqualTo(sample.getReviewerId());
        }
        if (sample.getProjectId() != null) {
            criteria.andProjectIdEqualTo(sample.getProjectId());
        }
        if (sample.getApproved() != null) {
            criteria.andApprovedEqualTo(sample.getApproved());
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    protected abstract static class GeneratedCriteria extends BaseCriteria {

        protected GeneratedCriteria() {
            super();
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdIsNull() {
            addCriterion("pullRequestId is null");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdIsNotNull() {
            addCriterion("pullRequestId is not null");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdEqualTo(Integer value) {
            addCriterion("pullRequestId =", value, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdNotEqualTo(Integer value) {
            addCriterion("pullRequestId <>", value, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdGreaterThan(Integer value) {
            addCriterion("pullRequestId >", value, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pullRequestId >=", value, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdLessThan(Integer value) {
            addCriterion("pullRequestId <", value, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdLessThanOrEqualTo(Integer value) {
            addCriterion("pullRequestId <=", value, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdIn(List<Integer> values) {
            addCriterion("pullRequestId in", values, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdNotIn(List<Integer> values) {
            addCriterion("pullRequestId not in", values, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdBetween(Integer value1, Integer value2) {
            addCriterion("pullRequestId between", value1, value2, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andPullRequestIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pullRequestId not between", value1, value2, "pullRequestId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdIsNull() {
            addCriterion("reviewerId is null");
            return (Criteria) this;
        }

        public Criteria andReviewerIdIsNotNull() {
            addCriterion("reviewerId is not null");
            return (Criteria) this;
        }

        public Criteria andReviewerIdEqualTo(Integer value) {
            addCriterion("reviewerId =", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdNotEqualTo(Integer value) {
            addCriterion("reviewerId <>", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdGreaterThan(Integer value) {
            addCriterion("reviewerId >", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("reviewerId >=", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdLessThan(Integer value) {
            addCriterion("reviewerId <", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdLessThanOrEqualTo(Integer value) {
            addCriterion("reviewerId <=", value, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdIn(List<Integer> values) {
            addCriterion("reviewerId in", values, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdNotIn(List<Integer> values) {
            addCriterion("reviewerId not in", values, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdBetween(Integer value1, Integer value2) {
            addCriterion("reviewerId between", value1, value2, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andReviewerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("reviewerId not between", value1, value2, "reviewerId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("projectId is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("projectId is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("projectId =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("projectId <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("projectId >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("projectId >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("projectId <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("projectId <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("projectId in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("projectId not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("projectId between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("projectId not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andApprovedIsNull() {
            addCriterion("approved is null");
            return (Criteria) this;
        }

        public Criteria andApprovedIsNotNull() {
            addCriterion("approved is not null");
            return (Criteria) this;
        }

        public Criteria andApprovedEqualTo(Boolean value) {
            addCriterion("approved =", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedNotEqualTo(Boolean value) {
            addCriterion("approved <>", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedGreaterThan(Boolean value) {
            addCriterion("approved >", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("approved >=", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedLessThan(Boolean value) {
            addCriterion("approved <", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedLessThanOrEqualTo(Boolean value) {
            addCriterion("approved <=", value, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedIn(List<Boolean> values) {
            addCriterion("approved in", values, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedNotIn(List<Boolean> values) {
            addCriterion("approved not in", values, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedBetween(Boolean value1, Boolean value2) {
            addCriterion("approved between", value1, value2, "approved");
            return (Criteria) this;
        }

        public Criteria andApprovedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("approved not between", value1, value2, "approved");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pull_request_reviewer
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 01 20:38:08 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}