package com.onboard.plugin.git.mapper;

import java.util.Date;

public class PullRequestActivityObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.id
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.projectId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.subject
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.action
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.commentId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.since
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String since;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.until
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String until;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.reviewId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer reviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.pullRequestId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer pullRequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.creatorId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.creatorName
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_activity.created
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.id
     *
     * @return the value of pull_request_activity.id
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.id
     *
     * @param id the value for pull_request_activity.id
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.projectId
     *
     * @return the value of pull_request_activity.projectId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.projectId
     *
     * @param projectId the value for pull_request_activity.projectId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.subject
     *
     * @return the value of pull_request_activity.subject
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.subject
     *
     * @param subject the value for pull_request_activity.subject
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.action
     *
     * @return the value of pull_request_activity.action
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.action
     *
     * @param action the value for pull_request_activity.action
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.commentId
     *
     * @return the value of pull_request_activity.commentId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.commentId
     *
     * @param commentId the value for pull_request_activity.commentId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.since
     *
     * @return the value of pull_request_activity.since
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getSince() {
        return since;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.since
     *
     * @param since the value for pull_request_activity.since
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setSince(String since) {
        this.since = since == null ? null : since.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.until
     *
     * @return the value of pull_request_activity.until
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getUntil() {
        return until;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.until
     *
     * @param until the value for pull_request_activity.until
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setUntil(String until) {
        this.until = until == null ? null : until.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.reviewId
     *
     * @return the value of pull_request_activity.reviewId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.reviewId
     *
     * @param reviewId the value for pull_request_activity.reviewId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.pullRequestId
     *
     * @return the value of pull_request_activity.pullRequestId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getPullRequestId() {
        return pullRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.pullRequestId
     *
     * @param pullRequestId the value for pull_request_activity.pullRequestId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setPullRequestId(Integer pullRequestId) {
        this.pullRequestId = pullRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.creatorId
     *
     * @return the value of pull_request_activity.creatorId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.creatorId
     *
     * @param creatorId the value for pull_request_activity.creatorId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.creatorName
     *
     * @return the value of pull_request_activity.creatorName
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.creatorName
     *
     * @param creatorName the value for pull_request_activity.creatorName
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_activity.created
     *
     * @return the value of pull_request_activity.created
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_activity.created
     *
     * @param created the value for pull_request_activity.created
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public PullRequestActivityObject(PullRequestActivityObject parent) {
        this.id = parent.getId();
        this.projectId = parent.getProjectId();
        this.subject = parent.getSubject();
        this.action = parent.getAction();
        this.commentId = parent.getCommentId();
        this.since = parent.getSince();
        this.until = parent.getUntil();
        this.reviewId = parent.getReviewId();
        this.pullRequestId = parent.getPullRequestId();
        this.creatorId = parent.getCreatorId();
        this.creatorName = parent.getCreatorName();
        this.created = parent.getCreated();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public PullRequestActivityObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public PullRequestActivityObject(int id) {
        this.id = id;
    }
}