package com.onboard.plugin.git.mapper;

public class PullRequestPushObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_push.id
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_push.pullRequestId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private Integer pullRequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request_push.pushId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private Integer pushId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_push.id
     *
     * @return the value of pull_request_push.id
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_push.id
     *
     * @param id the value for pull_request_push.id
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_push.pullRequestId
     *
     * @return the value of pull_request_push.pullRequestId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public Integer getPullRequestId() {
        return pullRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_push.pullRequestId
     *
     * @param pullRequestId the value for pull_request_push.pullRequestId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setPullRequestId(Integer pullRequestId) {
        this.pullRequestId = pullRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request_push.pushId
     *
     * @return the value of pull_request_push.pushId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public Integer getPushId() {
        return pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request_push.pushId
     *
     * @param pushId the value for pull_request_push.pushId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setPushId(Integer pushId) {
        this.pushId = pushId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public PullRequestPushObject(PullRequestPushObject parent) {
        this.id = parent.getId();
        this.pullRequestId = parent.getPullRequestId();
        this.pushId = parent.getPushId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public PullRequestPushObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public PullRequestPushObject(int id) {
        this.id = id;
    }
}