package com.onboard.plugin.git.mapper;

import com.onboard.plugin.git.mapper.PullRequestActivityExample;
import com.onboard.plugin.git.model.PullRequestActivity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PullRequestActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int countByExample(PullRequestActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int deleteByExample(PullRequestActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int insert(PullRequestActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int insertSelective(PullRequestActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    List<PullRequestActivity> selectByExample(PullRequestActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    PullRequestActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int updateByExampleSelective(@Param("record") PullRequestActivity record, @Param("example") PullRequestActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int updateByExample(@Param("record") PullRequestActivity record, @Param("example") PullRequestActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int updateByPrimaryKeySelective(PullRequestActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_activity
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    int updateByPrimaryKey(PullRequestActivity record);
}
