package com.onboard.plugin.git.mapper;

import java.util.Date;

public class PullRequestObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.id
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.source
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.destination
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.title
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.deleted
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.status
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.creatorId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.todoId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer todoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.creatorName
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.created
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.updated
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.projectId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.scopeId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer scopeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.sourceHash
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String sourceHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.destinationHash
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String destinationHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.repositoryId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer repositoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.companyId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pull_request.description
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.id
     *
     * @return the value of pull_request.id
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.id
     *
     * @param id the value for pull_request.id
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.source
     *
     * @return the value of pull_request.source
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.source
     *
     * @param source the value for pull_request.source
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.destination
     *
     * @return the value of pull_request.destination
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.destination
     *
     * @param destination the value for pull_request.destination
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.title
     *
     * @return the value of pull_request.title
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.title
     *
     * @param title the value for pull_request.title
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.deleted
     *
     * @return the value of pull_request.deleted
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.deleted
     *
     * @param deleted the value for pull_request.deleted
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.status
     *
     * @return the value of pull_request.status
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.status
     *
     * @param status the value for pull_request.status
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.creatorId
     *
     * @return the value of pull_request.creatorId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.creatorId
     *
     * @param creatorId the value for pull_request.creatorId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.todoId
     *
     * @return the value of pull_request.todoId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getTodoId() {
        return todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.todoId
     *
     * @param todoId the value for pull_request.todoId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setTodoId(Integer todoId) {
        this.todoId = todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.creatorName
     *
     * @return the value of pull_request.creatorName
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.creatorName
     *
     * @param creatorName the value for pull_request.creatorName
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.created
     *
     * @return the value of pull_request.created
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.created
     *
     * @param created the value for pull_request.created
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.updated
     *
     * @return the value of pull_request.updated
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.updated
     *
     * @param updated the value for pull_request.updated
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.projectId
     *
     * @return the value of pull_request.projectId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.projectId
     *
     * @param projectId the value for pull_request.projectId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.scopeId
     *
     * @return the value of pull_request.scopeId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getScopeId() {
        return scopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.scopeId
     *
     * @param scopeId the value for pull_request.scopeId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setScopeId(Integer scopeId) {
        this.scopeId = scopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.sourceHash
     *
     * @return the value of pull_request.sourceHash
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getSourceHash() {
        return sourceHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.sourceHash
     *
     * @param sourceHash the value for pull_request.sourceHash
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setSourceHash(String sourceHash) {
        this.sourceHash = sourceHash == null ? null : sourceHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.destinationHash
     *
     * @return the value of pull_request.destinationHash
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getDestinationHash() {
        return destinationHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.destinationHash
     *
     * @param destinationHash the value for pull_request.destinationHash
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setDestinationHash(String destinationHash) {
        this.destinationHash = destinationHash == null ? null : destinationHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.repositoryId
     *
     * @return the value of pull_request.repositoryId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.repositoryId
     *
     * @param repositoryId the value for pull_request.repositoryId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.companyId
     *
     * @return the value of pull_request.companyId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.companyId
     *
     * @param companyId the value for pull_request.companyId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pull_request.description
     *
     * @return the value of pull_request.description
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pull_request.description
     *
     * @param description the value for pull_request.description
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public PullRequestObject(PullRequestObject parent) {
        this.id = parent.getId();
        this.source = parent.getSource();
        this.destination = parent.getDestination();
        this.title = parent.getTitle();
        this.deleted = parent.getDeleted();
        this.status = parent.getStatus();
        this.creatorId = parent.getCreatorId();
        this.todoId = parent.getTodoId();
        this.creatorName = parent.getCreatorName();
        this.created = parent.getCreated();
        this.updated = parent.getUpdated();
        this.projectId = parent.getProjectId();
        this.scopeId = parent.getScopeId();
        this.sourceHash = parent.getSourceHash();
        this.destinationHash = parent.getDestinationHash();
        this.repositoryId = parent.getRepositoryId();
        this.companyId = parent.getCompanyId();
        this.description = parent.getDescription();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public PullRequestObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public PullRequestObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public PullRequestObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public PullRequestObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }
}