package com.onboard.plugin.git.mapper;

import com.onboard.plugin.git.mapper.PullRequestPushExample;
import com.onboard.plugin.git.model.PullRequestPush;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PullRequestPushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int countByExample(PullRequestPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int deleteByExample(PullRequestPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int insert(PullRequestPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int insertSelective(PullRequestPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    List<PullRequestPush> selectByExample(PullRequestPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    PullRequestPush selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") PullRequestPush record, @Param("example") PullRequestPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int updateByExample(@Param("record") PullRequestPush record, @Param("example") PullRequestPushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int updateByPrimaryKeySelective(PullRequestPush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pull_request_push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int updateByPrimaryKey(PullRequestPush record);
}
