package com.onboard.plugin.git.mapper;

public class PushObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.id
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.since
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private String since;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.until
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private String until;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.creatorId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.creatorName
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.repositoryId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private Integer repositoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.branchName
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.projectId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push.companyId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.id
     *
     * @return the value of push.id
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.id
     *
     * @param id the value for push.id
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.since
     *
     * @return the value of push.since
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public String getSince() {
        return since;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.since
     *
     * @param since the value for push.since
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setSince(String since) {
        this.since = since == null ? null : since.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.until
     *
     * @return the value of push.until
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public String getUntil() {
        return until;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.until
     *
     * @param until the value for push.until
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setUntil(String until) {
        this.until = until == null ? null : until.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.creatorId
     *
     * @return the value of push.creatorId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.creatorId
     *
     * @param creatorId the value for push.creatorId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.creatorName
     *
     * @return the value of push.creatorName
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.creatorName
     *
     * @param creatorName the value for push.creatorName
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.repositoryId
     *
     * @return the value of push.repositoryId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public Integer getRepositoryId() {
        return repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.repositoryId
     *
     * @param repositoryId the value for push.repositoryId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setRepositoryId(Integer repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.branchName
     *
     * @return the value of push.branchName
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.branchName
     *
     * @param branchName the value for push.branchName
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName == null ? null : branchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.projectId
     *
     * @return the value of push.projectId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.projectId
     *
     * @param projectId the value for push.projectId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push.companyId
     *
     * @return the value of push.companyId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push.companyId
     *
     * @param companyId the value for push.companyId
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public PushObject(PushObject parent) {
        this.id = parent.getId();
        this.since = parent.getSince();
        this.until = parent.getUntil();
        this.creatorId = parent.getCreatorId();
        this.creatorName = parent.getCreatorName();
        this.repositoryId = parent.getRepositoryId();
        this.branchName = parent.getBranchName();
        this.projectId = parent.getProjectId();
        this.companyId = parent.getCompanyId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public PushObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    public PushObject(int id) {
        this.id = id;
    }
}