package com.onboard.plugin.git.mapper;

import com.onboard.plugin.git.mapper.PushExample;
import com.onboard.plugin.git.model.Push;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int countByExample(PushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int deleteByExample(PushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int insert(Push record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int insertSelective(Push record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    List<Push> selectByExample(PushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    Push selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") Push record, @Param("example") PushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int updateByExample(@Param("record") Push record, @Param("example") PushExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int updateByPrimaryKeySelective(Push record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table push
     *
     * @mbggenerated Wed Apr 16 21:57:21 CST 2014
     */
    int updateByPrimaryKey(Push record);
}
