package com.onboard.plugin.git.mapper;

import com.onboard.plugin.git.mapper.RepositoryPrivilegeExample;
import com.onboard.plugin.git.model.RepositoryPrivilege;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepositoryPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int countByExample(RepositoryPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int deleteByExample(RepositoryPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int insert(RepositoryPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int insertSelective(RepositoryPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    List<RepositoryPrivilege> selectByExample(RepositoryPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    RepositoryPrivilege selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int updateByExampleSelective(@Param("record") RepositoryPrivilege record, @Param("example") RepositoryPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int updateByExample(@Param("record") RepositoryPrivilege record, @Param("example") RepositoryPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int updateByPrimaryKeySelective(RepositoryPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege
     *
     * @mbggenerated Fri Dec 06 16:07:16 CST 2013
     */
    int updateByPrimaryKey(RepositoryPrivilege record);
}
