package com.onboard.plugin.git.mapper;

import com.onboard.plugin.git.mapper.RepositoryBranchPrivilegeExample;
import com.onboard.plugin.git.model.RepositoryBranchPrivilege;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepositoryBranchPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int countByExample(RepositoryBranchPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int deleteByExample(RepositoryBranchPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int insert(RepositoryBranchPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int insertSelective(RepositoryBranchPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    List<RepositoryBranchPrivilege> selectByExample(RepositoryBranchPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    RepositoryBranchPrivilege selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int updateByExampleSelective(@Param("record") RepositoryBranchPrivilege record, @Param("example") RepositoryBranchPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int updateByExample(@Param("record") RepositoryBranchPrivilege record, @Param("example") RepositoryBranchPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int updateByPrimaryKeySelective(RepositoryBranchPrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repo_branch_privilege
     *
     * @mbggenerated Sun Dec 08 00:08:30 CST 2013
     */
    int updateByPrimaryKey(RepositoryBranchPrivilege record);
}
