package com.onboard.plugin.git.mapper;

import com.onboard.plugin.git.mapper.RepositoryPrivilegeUserExample;
import com.onboard.plugin.git.model.RepositoryPrivilegeUser;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepositoryPrivilegeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int countByExample(RepositoryPrivilegeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int deleteByExample(RepositoryPrivilegeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int insert(RepositoryPrivilegeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int insertSelective(RepositoryPrivilegeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    List<RepositoryPrivilegeUser> selectByExample(RepositoryPrivilegeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    RepositoryPrivilegeUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") RepositoryPrivilegeUser record, @Param("example") RepositoryPrivilegeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int updateByExample(@Param("record") RepositoryPrivilegeUser record, @Param("example") RepositoryPrivilegeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int updateByPrimaryKeySelective(RepositoryPrivilegeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    int updateByPrimaryKey(RepositoryPrivilegeUser record);
}
