package com.onboard.plugin.git.mapper;

import java.util.Date;

public class RepositoryObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.id
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.slug
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String slug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.name
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.deleted
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.projectId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.created
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.updated
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.updatedBranch
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private String updatedBranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.companyId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.id
     *
     * @return the value of repository.id
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.id
     *
     * @param id the value for repository.id
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.slug
     *
     * @return the value of repository.slug
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.slug
     *
     * @param slug the value for repository.slug
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.name
     *
     * @return the value of repository.name
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.name
     *
     * @param name the value for repository.name
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.deleted
     *
     * @return the value of repository.deleted
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.deleted
     *
     * @param deleted the value for repository.deleted
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.projectId
     *
     * @return the value of repository.projectId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.projectId
     *
     * @param projectId the value for repository.projectId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.created
     *
     * @return the value of repository.created
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.created
     *
     * @param created the value for repository.created
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.updated
     *
     * @return the value of repository.updated
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.updated
     *
     * @param updated the value for repository.updated
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.updatedBranch
     *
     * @return the value of repository.updatedBranch
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public String getUpdatedBranch() {
        return updatedBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.updatedBranch
     *
     * @param updatedBranch the value for repository.updatedBranch
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setUpdatedBranch(String updatedBranch) {
        this.updatedBranch = updatedBranch == null ? null : updatedBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.companyId
     *
     * @return the value of repository.companyId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.companyId
     *
     * @param companyId the value for repository.companyId
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public RepositoryObject(RepositoryObject parent) {
        this.id = parent.getId();
        this.slug = parent.getSlug();
        this.name = parent.getName();
        this.deleted = parent.getDeleted();
        this.projectId = parent.getProjectId();
        this.created = parent.getCreated();
        this.updated = parent.getUpdated();
        this.updatedBranch = parent.getUpdatedBranch();
        this.companyId = parent.getCompanyId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public RepositoryObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public RepositoryObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public RepositoryObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated Tue Mar 18 23:28:24 CST 2014
     */
    public RepositoryObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }
}