package com.onboard.plugin.git.mapper;

public class RepositoryPrivilegeUserObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository_privilege_user.id
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository_privilege_user.userId
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository_privilege_user.repositoryRrivilegeId
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    private Integer repositoryRrivilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository_privilege_user.id
     *
     * @return the value of repository_privilege_user.id
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository_privilege_user.id
     *
     * @param id the value for repository_privilege_user.id
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository_privilege_user.userId
     *
     * @return the value of repository_privilege_user.userId
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository_privilege_user.userId
     *
     * @param userId the value for repository_privilege_user.userId
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository_privilege_user.repositoryRrivilegeId
     *
     * @return the value of repository_privilege_user.repositoryRrivilegeId
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public Integer getRepositoryRrivilegeId() {
        return repositoryRrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository_privilege_user.repositoryRrivilegeId
     *
     * @param repositoryRrivilegeId the value for repository_privilege_user.repositoryRrivilegeId
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public void setRepositoryRrivilegeId(Integer repositoryRrivilegeId) {
        this.repositoryRrivilegeId = repositoryRrivilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public RepositoryPrivilegeUserObject(RepositoryPrivilegeUserObject parent) {
        this.id = parent.getId();
        this.userId = parent.getUserId();
        this.repositoryRrivilegeId = parent.getRepositoryRrivilegeId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public RepositoryPrivilegeUserObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository_privilege_user
     *
     * @mbggenerated Thu Dec 05 14:52:11 CST 2013
     */
    public RepositoryPrivilegeUserObject(int id) {
        this.id = id;
    }
}