package com.onboard.plugin.git.mapper;

import java.util.Date;

public class ReviewObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.creatorId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.creatorName
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.file
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.line
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer line;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.deleted
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.projectId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.pullRequestId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Integer pullRequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.created
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.updated
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.line_type
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String line_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.since
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String since;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.until
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String until;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.content
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.id
     *
     * @return the value of review.id
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.id
     *
     * @param id the value for review.id
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.creatorId
     *
     * @return the value of review.creatorId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.creatorId
     *
     * @param creatorId the value for review.creatorId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.creatorName
     *
     * @return the value of review.creatorName
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.creatorName
     *
     * @param creatorName the value for review.creatorName
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.file
     *
     * @return the value of review.file
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.file
     *
     * @param file the value for review.file
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.line
     *
     * @return the value of review.line
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.line
     *
     * @param line the value for review.line
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setLine(Integer line) {
        this.line = line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.deleted
     *
     * @return the value of review.deleted
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.deleted
     *
     * @param deleted the value for review.deleted
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.projectId
     *
     * @return the value of review.projectId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.projectId
     *
     * @param projectId the value for review.projectId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.pullRequestId
     *
     * @return the value of review.pullRequestId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Integer getPullRequestId() {
        return pullRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.pullRequestId
     *
     * @param pullRequestId the value for review.pullRequestId
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setPullRequestId(Integer pullRequestId) {
        this.pullRequestId = pullRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.created
     *
     * @return the value of review.created
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.created
     *
     * @param created the value for review.created
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.updated
     *
     * @return the value of review.updated
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.updated
     *
     * @param updated the value for review.updated
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.line_type
     *
     * @return the value of review.line_type
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getLine_type() {
        return line_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.line_type
     *
     * @param line_type the value for review.line_type
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setLine_type(String line_type) {
        this.line_type = line_type == null ? null : line_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.since
     *
     * @return the value of review.since
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getSince() {
        return since;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.since
     *
     * @param since the value for review.since
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setSince(String since) {
        this.since = since == null ? null : since.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.until
     *
     * @return the value of review.until
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getUntil() {
        return until;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.until
     *
     * @param until the value for review.until
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setUntil(String until) {
        this.until = until == null ? null : until.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.content
     *
     * @return the value of review.content
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.content
     *
     * @param content the value for review.content
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public ReviewObject(ReviewObject parent) {
        this.id = parent.getId();
        this.creatorId = parent.getCreatorId();
        this.creatorName = parent.getCreatorName();
        this.file = parent.getFile();
        this.line = parent.getLine();
        this.deleted = parent.getDeleted();
        this.projectId = parent.getProjectId();
        this.pullRequestId = parent.getPullRequestId();
        this.created = parent.getCreated();
        this.updated = parent.getUpdated();
        this.line_type = parent.getLine_type();
        this.since = parent.getSince();
        this.until = parent.getUntil();
        this.content = parent.getContent();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public ReviewObject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public ReviewObject(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public ReviewObject(boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Sun Dec 01 20:38:08 CST 2013
     */
    public ReviewObject(int id, boolean deleted) {
        this.id = id;
        this.deleted = deleted;
    }
}